// SPDX-License-Identifier: MIT
// GENERATED FROM docs/openapi.yaml — DO NOT EDIT BY HAND.
// Regenerate with: npm run client:generate

export interface ApiOperation {
  name: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS" | "HEAD";
  path: string;
  summary: string;
  tags: string[];
  requestBody: boolean;
}

export type ApiOperationName =
  | "deleteApiAuthSession"
  | "deleteApiKeys"
  | "deleteApiPaymentsId"
  | "deleteApiScheduled"
  | "deleteApiWebhooks"
  | "getApiAnalytics"
  | "getApiAssetsMetadata"
  | "getApiAuditLog"
  | "getApiAuditLogExport"
  | "getApiAuditLogSse"
  | "getApiAuthChallenge"
  | "getApiBatches"
  | "getApiBatchesId"
  | "getApiBatchesSummary"
  | "getApiContracts"
  | "getApiCron"
  | "getApiCsrf"
  | "getApiEscrows"
  | "getApiEscrowsId"
  | "getApiEvents"
  | "getApiEventsHistory"
  | "getApiFeeConfig"
  | "getApiFeeConfigCollector"
  | "getApiFeeConfigHistory"
  | "getApiGovernanceProposals"
  | "getApiGovernanceProposalsId"
  | "getApiHealth"
  | "getApiHealthLive"
  | "getApiHooks"
  | "getApiKeys"
  | "getApiKeysStats"
  | "getApiMetrics"
  | "getApiMultisig"
  | "getApiMultisigRequests"
  | "getApiPauseState"
  | "getApiPayments"
  | "getApiPaymentsExport"
  | "getApiPaymentsId"
  | "getApiPolicyVersions"
  | "getApiRbac"
  | "getApiRecurring"
  | "getApiRecurringId"
  | "getApiRefunds"
  | "getApiRequests"
  | "getApiScheduled"
  | "getApiScheduledRun"
  | "getApiStats"
  | "getApiStreams"
  | "getApiStreamsId"
  | "getApiTimelock"
  | "getApiWebhooks"
  | "getApiWebhooksId"
  | "getApiWebhooksIdDeliveries"
  | "getApiWebhooksIdDeliveriesDeliveryId"
  | "getApiWebhooksIdTest"
  | "patchApiHooksId"
  | "patchApiKeys"
  | "patchApiPaymentsId"
  | "patchApiRecurring"
  | "patchApiRecurringId"
  | "patchApiRefundsId"
  | "patchApiWebhooks"
  | "postApiAuthSession"
  | "postApiBatches"
  | "postApiBatchesId"
  | "postApiCron"
  | "postApiCspReport"
  | "postApiEscrows"
  | "postApiGovernanceExecute"
  | "postApiGovernanceProposals"
  | "postApiGovernanceVote"
  | "postApiHooks"
  | "postApiJobsProcessDueRecurring"
  | "postApiKeys"
  | "postApiKeysIdRotate"
  | "postApiMultisig"
  | "postApiMultisigApprove"
  | "postApiMultisigExecute"
  | "postApiMultisigPropose"
  | "postApiPayments"
  | "postApiPaymentsCancel"
  | "postApiPaymentsRetry"
  | "postApiRecurring"
  | "postApiRefunds"
  | "postApiRequests"
  | "postApiScheduled"
  | "postApiScheduledRun"
  | "postApiStreams"
  | "postApiWebhooks"
  | "postApiWebhooksIdDeliveriesDeliveryIdRedeliver"
  | "postApiWebhooksIdReplay"
  | "postApiWebhooksIdTest";

export declare const API_OPERATIONS: ReadonlyArray<ApiOperation>;
export declare const OPERATION_BY_NAME: Record<ApiOperationName, ApiOperation>;
